blank_issues_enabled: true
contact_links:
 - name: Add new ToDo
 　　　　about: made by config.yml
 
 　　　　url: https://github.com/Ika-Taro/Keku-cafe/issues/new?template=custom.md&projects=Ika-Taro%2FKeku-cafe%2F1&labels=Keku-cafe
